name: topology
channels:
- pytorch
- pyg
- gurobi
- conda-forge
dependencies:
- pyvista=0.43.3
- matplotlib=3.8.4
- trame=3.5.2
- libopenblas=0.3.24
- imgaug=0.4.0
- libgomp=13.2.0
- torchaudio=2.1.1
- gurobi=11.0.1
- pip=24.0
- cupy=13.0.0
- mpi4py=3.1.6
- pyg=2.4.0
- scikit-sparse=0.4.12
- jupyter=1.0.0
- mapie=0.8.2
- gradio=4.21.0
- torchvision=0.16.1

